### ISSUE TITLE
Блокировка через техподдержку

### ISSUE THREAD

**Issue by Lebedevsd** [zhovner/how-skype-fix-vulnerabilities#7]
Ребят отпишите, кто переводит эту секцию, что бы никому не переводить в пустую.

**Comment by Aelphy** [comment]
Я возьму.

**Comment by i2gor87** [comment]
Прошу прощения, не зашел сразу и не отписался. Послал пулл реквест на свой перевод - можно сравнить и в случае чего взять только понравившееся.

**Comment by Aelphy** [comment]
Прошу прощения, я промахнулся секцией, я перевел другую часть.
